### ISSUE TITLE
기념일 커스텀 지원

### ISSUE THREAD

**Issue by spearkkk** [hyunbinseo/holidays-kr#1]
안녕하세요. 
혹시 기념일 명칭에 대해서 커스텀하게 설정할 수 있도록 지원이 가능할까요? 
query string으로 key-value 값으로 받아서 지원하면 어떨까 싶어서요.

`{url}?12-25=아무것도아닌날&01-01=첫날`

**Comment by hyunbinseo** [comment]
현재는 쿼리문을 지원하지 않는 정적 호스팅 방식이어서 어렵습니다.

Google 캘린더를 사용하고 계시다면, 연도별 CSV 파일을 수정해 직접 불러오는 방식으로 사용하셔도 될 것 같습니다.

새로운 연도의 공휴일 정보가 추가됐을 때 이메일 알림이 발송되도록 할 수도 있고요. (향후 Releases 기능을 사용하면)
