### ISSUE TITLE
"SERVICE_KEY_IS_NOT_REGISTERED_ERROR"

### ISSUE THREAD

**Issue by hmmhmmhm** [hyunbinseo/holidays-kr#12]
깃허브에 올라온 내용이 npm 모듈에 반영이 안 된 것 같네요, 저 서비스 키는 어디서 발급받나요?

**Comment by hmmhmmhm** [comment]
아 동일한 명칭의 깃허브 주소를 혼동했네요 감사합니다.

**Comment by hyunbinseo** [comment]
안녕하세요, 혹시 본 패키지에서 헷갈리는 부분이 있을까요? 개선할 여지가 있으면 편하게 댓글 남겨주세요.
