### ISSUE TITLE
대체공휴일 안내오류 (석가탄신일)

### ISSUE THREAD

**Issue by jesustar** [hyunbinseo/holidays-kr#2]
안녕하세요, 클량에서 공휴일 정보를 보고 구글 캘린더를 버리고, 개발자님의 캘린더를 활용하고 있습니다.

두둥!! 그런데, 구글 캘린더의 대체공휴일 오류(23년 10월 2일이 추석 대체공휴일이라고 표기)는 수정이 되었는데...
개발자님의 캘린더는 대체공휴일 오류 (23년 5월 29일이 석가탄신일 대체공휴일이라고 표기) 가 있네요.

'공휴일에 관한 법률'은 공휴일이 주말과 겹치면 대체공휴일을 적용하도록 돼 있지만, 크리스마스와 석가탄신일은 대체공휴일 대상에 포함되지 않습니다.

인사혁신처에서 대체공휴일 확대를 추진한다고 하나, 현재 기준으로는 석가탄신일 대체공휴일은 잘못된 정보이니 서둘러 수정하시는게 좋을 듯 합니다.

감사합니다.

**Comment by hyunbinseo** [comment]
안녕하세요,

작년 12월 경에 [발표된 내용](https://www.hankyung.com/society/article/2022122116397) 때문에 5/29을 대체 공휴일로 추가해둔 상태입니다. https://github.com/hyunbinseo/holidays-kr/commit/08a757dac0e7a0f2a73113961b3e28264b5fa2b2

> 대통령령은 입법예고, 차관·국무회의를 거쳐 공포하며 최소 90일 이상 소요되는 것으로 전해졌다. 이에 따라 올해 성탄절은 지정이 어려울 것으로 예상되며, 내년 부처님 오신 날이 5월 27일 토요일이어서 대체휴일 지정 시 다음 주 월요일인 29일 쉴 수 있게 된다.

기정사실이라고 생각돼서 넣어뒀는데, 우선은 빼두고 추후에 다시금 추가하는 게 나으려나요?

**Comment by hyunbinseo** [comment]
예정으로 변경했습니다. https://github.com/hyunbinseo/holidays-kr/commit/a0c34adbea8759ad2d60230bebb4b54f06f1776b

```
['2023-05-29', '예정-대체공휴일(부처님 오신 날)'],
```
