### ISSUE TITLE
2023년도 대체공휴일 수정

### ISSUE THREAD

**Issue by hyunbinseo** [hyunbinseo/holidays-kr#3]
> 인사혁신처는 이 같은 내용을 담은 '관공서의 공휴일에 관한 규정' 개정안(대통령령)을 오는 16일부터 입법예고 한다고 15일 밝혔다.
>
> 다음 달 5일까지인 입법예고 기간에 인사처는 대체공휴일 지정에 관한 국민 의견을 받을 예정이다. 법제처 심사, 차관·국무회의, 대통령 재가를 거치면 관보에 정식 공포된다.
>
> 큰 이변이 없다면 다음 달 중으로 대통령 재가까지 완료돼 올해 부처님오신날부터 적용된다. — [연합뉴스](https://v.daum.net/v/20230315110021028)

**Comment by roeniss** [comment]
@hyunbinseo 부처님오신날이 토요일이고, 그 다음주 월요일이 대체공휴일로 확정되었습니다. @hyunbinseo 님이 수동으로 제어하지 않아도 자동으로 적용될 줄 알았는데...매번 수작업으로 작업하셔야 처리되는 방식인가요? 😢

**Comment by hyunbinseo** [comment]
> 법제처 심사, 차관·국무회의, 대통령 재가를 거치면 관보에 정식 공포된다.

아직 관보에 정식 공포되지 않은 것으로 알고 있습니다. [네이버 캘린더]에도 적용되어 있지 않고요.

[네이버 캘린더]: https://calendar.naver.com/publicCalendar?publishedKey=07d7272aa0f95ff42726e3f518d77d2e5b11be0832d29ecca03c6a28caa676d240afc5c7b56b2633

@roeniss 혹여나 관보에 공포되었다면 관련 자료 공유 부탁드립니다. 캘린더 수정해 두겠습니다.

---

연도별 공휴일 정보 자체는 수기로 입력합니다. 이게 자동으로 가공되어 여러 형태로 제공됩니다. (ICS 호스팅, npm 패키지 등)

**Comment by roeniss** [comment]
따로 자료는 찾아보지 않았습니다. 그런 식으로 작동하는군요. 고생이 많으십니다...

**Comment by hyunbinseo** [comment]
> 인사혁신처는 2일 윤석열 대통령 주재로 열린 국무회의에서 부처님오신날과 성탄절에 대체공휴일을 운영하는 내용의 ‘관공서의 공휴일에 관한 규정’ 개정안이 의결됐다고 밝혔다. 개정 법령은 대통령 재가 후 이번 주 관보에 게재돼 즉시 효력이 발생한다. — [동아일보](https://v.daum.net/v/20230502111136866)

**Comment by hyunbinseo** [comment]
Fixed in https://github.com/hyunbinseo/holidays-kr/commit/3ea0d2bf14398e7406b032818fb0143f7dcc6cd8

**Comment by chanheelee-dev** [comment]
고생 많으십니다~ 혹시 도네이션 같은거 열어 두시면 커피값 정도라도 한잔 보내고 싶네요 ㅎㅎ

**Comment by hyunbinseo** [comment]
@chanheelee-dev 감사합니다. 당장은 기부를 열어둘 예정이 없어서 마음만 받겠습니다.
