### ISSUE TITLE
제안

### ISSUE THREAD

**Issue by SSaMKJ** [hyunbinseo/holidays-kr#6]
안녕하세요.
만들어주신 대한민국 공휴일을 잘 사용하고 있습니다.
한가지 부탁드리고 싶은 것이 있습니다.
공휴일 달력외에 국가기념일 캘린더도 만들어 주실 수 있을까 해서요.
데이터는 https://www.mois.go.kr/chd/sub/a05/feteDay/screen.do 여기에 있네요.

우려되는 점은 "국경일"과 "기념일"이 휴일인 경우도 있고 아닌 경우도 있어서 똑 같은 내용이 2중으로 노출되는 현상이 있을 것 같아요.
그래서 2가지 캘린더가 필요할 것 같아요. 
1. 대한민국 국경일+기념일 (공휴일 포함)
2. 대한민국 국경일+기념일 (공휴일 제외)

**Comment by hyunbinseo** [comment]
취지나 사용처가 궁금합니다.

국경일 및 기념일을 Google 캘린더 등에 넣어놓고 보기 위함일까요?

아니면 CSV, JSON 등의 형태로 가공된 파일이 필요하신 걸까요?

공휴일을 제외하지 않는다면 충분히 구현 가능할 것 같습니다.

**Comment by SSaMKJ** [comment]
빠른 답변 감사합니다.

캘린더에 추가로 넣기 위함입니다.

총 3개의 result data가 있고, url에 따라 다른 값을 return 해준다면 공휴일 제외도 가능하지 않을까요?

**Comment by hyunbinseo** [comment]
개발 및 배포의 편의를 위해 국경일⋅기념일 캘린더는 1종만 배포했으면 하는 바람입니다. 

늦어도 3분기까지는 배포할 수 있도록 준비해 보겠습니다. 당장은 여건이 안 되네요.

**Comment by hyunbinseo** [comment]
[대한민국의 기념일]이 배포되었습니다.

[대한민국의 기념일]: https://github.com/hyunbinseo/holidays-kr/blob/main/.github/ANNIVERSARIES.md
